// Code generated by go generate; DO NOT EDIT.
package repository

import (
	"errors"
	"github.com/mhcvintar/repo-gen/models"
	"gorm.io/gorm"
)

type userRepositoryImpl struct {
	db *gorm.DB
}

var _ UserRepository = (*userRepositoryImpl)(nil)

func NewUserRepository(db *gorm.DB) UserRepository {
	return &userRepositoryImpl{
		db: db,
	}
}

func (r *userRepositoryImpl) FindByName(name string) (*models.User, error) {
	var result models.User
	dbResult := r.db.Where("name = ?", name).First(&result)
	if dbResult.Error != nil {
		if errors.Is(dbResult.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, dbResult.Error
	}
	return &result, nil
}

func (r *userRepositoryImpl) FindByEmail(email string) (*models.User, error) {
	var result models.User
	dbResult := r.db.Where("email = ?", email).First(&result)
	if dbResult.Error != nil {
		if errors.Is(dbResult.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, dbResult.Error
	}
	return &result, nil
}

